default:
    description: page
    fields:
        name:
            title: url name
            type: text
            widget: text
            write_privilege:
                privilege: "midcom:urlname"
        title:
            type: text
            widget: text
            required: true
        content:
            title: content
            type: text
            type_config:
                output_mode: html
            widget: fckeditor
        component:
            title: component
            type: select
            type_config:
                options:
                    midcom_core: None
                    net_nemein_news: News folder
            widget: select
            widget_config:
                height: 1